apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: nvidia.ai.enterprise.operator.1.0.0
spec:
  refName: nvidia.ai.enterprise.operator
  version: 1.0.0
  releaseNotes: |
    Initial release of the simple app package
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        ngc_email_address:
          type: string
          description: Email address used for Nvidia NGC Portal.
          default: wrightmi@vmware.com
        ngc_api_key:
          type: string
          description: Nvidia NGC API Key.
          default: 1231231ababab
        hello_msg:
          type: string
          description: Name used in hello message from app when app is pinged.
          default: stranger
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.services.edge.wrightcode.io/gpu/nvidia-gpu-operator:1.0.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
